printf(
"Suricata Configuration:\n"
"  DPDK support:                            yes\n"
"  AF_PACKET support:                       no\n"
"  eBPF support:                            no\n"
"  XDP support:                             no\n"
"  PF_RING support:                         no\n"
"  NFQueue support:                         no\n"
"  NFLOG support:                           no\n"
"  IPFW support:                            no\n"
"  Netmap support:                          no \n"
"  DAG enabled:                             no\n"
"  Napatech enabled:                        no\n"
"  WinDivert enabled:                       no\n"
"\n"
"  Unix socket enabled:                     yes\n"
"  Detection enabled:                       yes\n"
"\n"
"  Libmagic support:                        yes\n"
"  libnss support:                          yes\n"
"  libnspr support:                         yes\n"
"  libjansson support:                      yes\n"
"  hiredis support:                         no\n"
"  hiredis async with libevent:             no\n"
"  Prelude support:                         no\n"
"  PCRE jit:                                yes\n"
"  LUA support:                             no\n"
"  libluajit:                               no\n"
"  GeoIP2 support:                          no\n"
"  Non-bundled htp:                         no\n"
"  Hyperscan support:                       yes\n"
"  Libnet support:                          yes\n"
"  liblz4 support:                          yes\n"
"  HTTP2 decompression:                     no\n"
"\n"
"  Rust support:                            yes\n"
"  Rust strict mode:                        no\n"
"  Rust compiler path:                      /home/C402/.cargo/bin/rustc\n"
"  Rust compiler version:                   rustc 1.52.1 (9bc8c42bb 2021-05-09)\n"
"  Cargo path:                              /home/C402/.cargo/bin/cargo\n"
"  Cargo version:                           cargo 1.52.0 (69767412a 2021-04-21)\n"
"  Cargo vendor:                            yes\n"
"\n"
"  Python support:                          yes\n"
"  Python path:                             /usr/bin/python3\n"
"  Python distutils                         yes\n"
"  Python yaml                              yes\n"
"  Install suricatactl:                     yes\n"
"  Install suricatasc:                      yes\n"
"  Install suricata-update:                 yes\n"
"\n"
"  Profiling enabled:                       no\n"
"  Profiling locks enabled:                 no\n"
"\n"
"  Plugin support (experimental):           yes\n"
"\n"
"Development settings:\n"
"  Coccinelle / spatch:                     no\n"
"  Unit tests enabled:                      no\n"
"  Debug output enabled:                    no\n"
"  Debug validation enabled:                no\n"
"\n"
"Generic build parameters:\n"
"  Installation prefix:                     /home/C402/liqiang/dev_suricata\n"
"  Configuration directory:                 /home/C402/liqiang/dev_suricata/etc/suricata/\n"
"  Log directory:                           /home/C402/liqiang/dev_suricata/var/log/suricata/\n"
"\n"
"  --prefix                                 /home/C402/liqiang/dev_suricata\n"
"  --sysconfdir                             /home/C402/liqiang/dev_suricata/etc\n"
"  --localstatedir                          /home/C402/liqiang/dev_suricata/var\n"
"  --datarootdir                            /home/C402/liqiang/dev_suricata/share\n"
"\n"
"  Host:                                    x86_64-pc-linux-gnu\n"
"  Compiler:                                gcc (exec name) / g++ (real)\n"
"  GCC Protect enabled:                     no\n"
"  GCC march native enabled:                yes\n"
"  GCC Profile enabled:                     no\n"
"  Position Independent Executable enabled: no\n"
"  CFLAGS                                   -g -O2 -std=gnu99 -march=native -I${srcdir}/../rust/gen -I${srcdir}/../rust/dist\n"
"  PCAP_CFLAGS                               \n"
"  SECCFLAGS                                \n"
);
